// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: TimeEntry.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

public sealed record ApprovalResult(bool Ok, string? Message);
