// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Employee.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

public enum ContactMethod
{
    Email,
    Phone,
    None
}
