// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Employee.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

public sealed record Employee(
    Guid Id,
    string FirstName,
    string LastName,
    string Email,
    DateOnly HireDate,
    ContractType ContractType,
    ContactInfo? Contact,
    EmployeeState State
);
