// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Employee.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

/// <summary>Lifecycle states for <see cref="Employee"/>.</summary>
public enum EmployeeState
{
    Onboarding,
    Active,
    OnLeave,
    Terminated
}
