// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Employee.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

/// <summary>
/// Command on <see cref="Employee"/>.
/// Returns: OnboardResult
/// Side effect: Activated
/// </summary>
public sealed record Onboard(string FirstName, string LastName, string Email, DateOnly HireDate, ContractType ContractType);

/// <summary>
/// Command on <see cref="Employee"/>.
/// Returns: ActivationResult
/// Side effect: Activated
/// </summary>
public sealed record Activate();

/// <summary>
/// Command on <see cref="Employee"/>.
/// Returns: LeaveResult
/// Side effect: LeaveStarted
/// </summary>
public sealed record GoOnLeave(string? Reason);

/// <summary>
/// Command on <see cref="Employee"/>.
/// Returns: ReturnResult
/// Side effect: Returned
/// </summary>
public sealed record Return();

/// <summary>
/// Command on <see cref="Employee"/>.
/// Returns: TerminationResult
/// Side effect: Terminated
/// </summary>
public sealed record Terminate(string Reason);
