// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Employee.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

public sealed record LeaveResult(bool Ok, string? Message);
