// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Project.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

public sealed record PlanResult(bool Ok, string? Message);
