// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Project.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

/// <summary>
/// Command on <see cref="Project"/>.
/// Returns: PlanResult
/// Side effect: Started
/// </summary>
public sealed record Plan(string Name, string Code, DateOnly StartDate, DateOnly? TargetEndDate, Guid LeadId);

/// <summary>
/// Command on <see cref="Project"/>.
/// Returns: StartResult
/// Side effect: Started
/// </summary>
public sealed record Start();

/// <summary>
/// Command on <see cref="Project"/>.
/// Returns: HoldResult
/// Side effect: Held
/// </summary>
public sealed record Hold(string? Reason);

/// <summary>
/// Command on <see cref="Project"/>.
/// Returns: ResumeResult
/// Side effect: Resumed
/// </summary>
public sealed record Resume();

/// <summary>
/// Command on <see cref="Project"/>.
/// Returns: CompleteResult
/// Side effect: Completed
/// </summary>
public sealed record Complete();

/// <summary>
/// Command on <see cref="Project"/>.
/// Returns: CancelResult
/// Side effect: Cancelled
/// </summary>
public sealed record Cancel(string Reason);
