// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Project.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

/// <summary>Domain event emitted by <see cref="Project"/>.</summary>
public sealed record Started(DateTime StartedAt);

/// <summary>Domain event emitted by <see cref="Project"/>.</summary>
public sealed record Held(DateTime HeldAt, string? Reason);

/// <summary>Domain event emitted by <see cref="Project"/>.</summary>
public sealed record Resumed(DateTime ResumedAt);

/// <summary>Domain event emitted by <see cref="Project"/>.</summary>
public sealed record Completed(DateTime CompletedAt);

/// <summary>Domain event emitted by <see cref="Project"/>.</summary>
public sealed record Cancelled(DateTime CancelledAt, string Reason);
