// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Project.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

public sealed record Project(
    Guid Id,
    string Name,
    string Code,
    DateOnly StartDate,
    DateOnly? TargetEndDate,
    Guid Lead,
    ProjectState State
);
