// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Project.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

/// <summary>Lifecycle states for <see cref="Project"/>.</summary>
public enum ProjectState
{
    Planned,
    Active,
    OnHold,
    Completed,
    Cancelled
}
