// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: TimeEntry.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

public sealed record TimeEntry(
    Guid Id,
    DateOnly Date,
    decimal Hours,
    bool Billable,
    string? Description,
    string? RejectionReason,
    Guid Employee,
    Guid Project,
    Guid Submitter,
    Guid? Approver,
    TimeEntryState State
);
