// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: TimeEntry.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

/// <summary>
/// Command on <see cref="TimeEntry"/>.
/// Returns: SubmissionResult
/// Side effect: Submitted
/// </summary>
public sealed record Submit();

/// <summary>
/// Command on <see cref="TimeEntry"/>.
/// Returns: ApprovalResult
/// Side effect: Approved
/// </summary>
public sealed record Approve(Guid ApproverId);

/// <summary>
/// Command on <see cref="TimeEntry"/>.
/// Returns: RejectionResult
/// Side effect: Rejected
/// </summary>
public sealed record Reject(Guid ApproverId, string Reason);
