// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: TimeEntry.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

/// <summary>Domain event emitted by <see cref="TimeEntry"/>.</summary>
public sealed record Submitted(DateTime SubmittedAt);

/// <summary>Domain event emitted by <see cref="TimeEntry"/>.</summary>
public sealed record Approved(Guid ApproverId, DateTime ApprovedAt);

/// <summary>Domain event emitted by <see cref="TimeEntry"/>.</summary>
public sealed record Rejected(Guid ApproverId, string Reason);

/// <summary>Domain event emitted by <see cref="TimeEntry"/>.</summary>
public sealed record Resubmitted();

/// <summary>Domain event emitted by <see cref="TimeEntry"/>.</summary>
public sealed record Reopened(Guid ReopenerId, string Reason);
