// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: TimeEntry.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

/// <summary>Lifecycle states for <see cref="TimeEntry"/>.</summary>
public enum TimeEntryState
{
    Draft,
    Submitted,
    Approved,
    Rejected,
    Reopened
}
