// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Hr.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

public enum ContractType
{
    CDI,
    CDD,
    Freelance,
    Intern
}
