// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Hr.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

public sealed record ContactInfo(string Email, string? Phone);
