// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Hr.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

/// <summary>Domain event emitted by <see cref="Employee"/>.</summary>
public sealed record Activated(DateTime ActivatedAt);

/// <summary>Domain event emitted by <see cref="Employee"/>.</summary>
public sealed record Terminated(DateTime TerminatedAt, string Reason);
