// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Hr.gravity
// </auto-generated>

using System;

namespace AcmeCo.Domain.hr;

/// <summary>
/// Command on <see cref="Employee"/>.
/// Returns: OnboardResult
/// Side effect: Activated
/// </summary>
public sealed record Onboard(string FirstName, string LastName, string Email, DateOnly HireDate, ContractType ContractType);

/// <summary>
/// Command on <see cref="Employee"/>.
/// Returns: TerminationResult
/// Side effect: Terminated
/// </summary>
public sealed record Terminate(string Reason);
