// <auto-generated>
//     This file was generated by Gravity DSL.
//     Source: Hr.gravity
// </auto-generated>

namespace AcmeCo.Domain.hr;

public sealed record TerminationResult(bool Ok, string? Message);
