using System.Collections.Generic;
using System.Text;

namespace Gravity.Dsl.Emitter.PostgresDdl.Render;

/// <summary>
/// Deterministic SQL statement formatter helpers. Constants pin the indent
/// width and line-ending convention required by FR-454; banned-APIs analyzer
/// keeps <c>Environment.NewLine</c>, <c>StringBuilder.AppendLine</c>,
/// timestamps, and machine-identity reads out of the codebase.
/// </summary>
internal static class SqlWriter
{
    /// <summary>LF newline. FR-454 — never <c>Environment.NewLine</c>.</summary>
    public const string Lf = "\n";

    /// <summary>Indentation unit; 4 spaces matches the pg_dump default.</summary>
    public const string Indent = "    ";

    /// <summary>
    /// Render the canonical three-line file header. No timestamp, no machine
    /// name (FR-454 / G-8). The trailing blank line is the consumer's job
    /// (handled by <see cref="Compose"/>).
    /// </summary>
    public static string Header(string fqn, int version)
    {
        return
            "-- Gravity DSL — generated by gravc (target: postgres-ddl)" + Lf +
            "-- source: " + fqn + " version " + version.ToString(System.Globalization.CultureInfo.InvariantCulture) + Lf +
            "-- DO NOT EDIT — re-run the emitter to regenerate.";
    }

    /// <summary>
    /// Join non-empty <paramref name="blocks"/> with one blank line between
    /// them and ensure the result ends with exactly one trailing newline.
    /// </summary>
    public static string Compose(params string[] blocks)
    {
        var sb = new StringBuilder();
        bool first = true;
        foreach (var b in blocks)
        {
            if (string.IsNullOrEmpty(b)) continue;
            if (!first)
            {
                sb.Append(Lf);
                sb.Append(Lf);
            }
            sb.Append(b);
            first = false;
        }
        if (sb.Length == 0) return string.Empty;
        // Trim any trailing newlines and re-append exactly one.
        while (sb.Length > 0 && sb[sb.Length - 1] == '\n')
        {
            sb.Length--;
        }
        sb.Append(Lf);
        return sb.ToString();
    }

    /// <summary>
    /// Wrap a body in the standard PostgreSQL idempotency envelope (PG lacks
    /// <c>CREATE TYPE IF NOT EXISTS</c> / <c>ADD CONSTRAINT IF NOT EXISTS</c>).
    /// </summary>
    public static string WrapIdempotent(string innerStatement)
    {
        return
            "DO $$" + Lf +
            "BEGIN" + Lf +
            IndentLines(innerStatement) + Lf +
            "EXCEPTION" + Lf +
            "    WHEN duplicate_object THEN NULL;" + Lf +
            "END $$;";
    }

    /// <summary>Prefix each line of <paramref name="body"/> with one indent unit.</summary>
    public static string IndentLines(string body)
    {
        if (string.IsNullOrEmpty(body)) return body;
        var lines = body.Split('\n');
        var sb = new StringBuilder();
        for (int i = 0; i < lines.Length; i++)
        {
            if (i > 0) sb.Append(Lf);
            if (lines[i].Length > 0)
            {
                sb.Append(Indent);
                sb.Append(lines[i]);
            }
        }
        return sb.ToString();
    }

    /// <summary>Join an enumerable of statement strings with one blank line between each.</summary>
    public static string JoinBlocks(IEnumerable<string> blocks)
    {
        var sb = new StringBuilder();
        bool first = true;
        foreach (var b in blocks)
        {
            if (string.IsNullOrEmpty(b)) continue;
            if (!first)
            {
                sb.Append(Lf);
                sb.Append(Lf);
            }
            sb.Append(b);
            first = false;
        }
        return sb.ToString();
    }
}
