using System;
using System.Globalization;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Formatting;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Options;

namespace Gravity.Dsl.Emitter.CSharp;

/// <summary>
/// Wraps Roslyn's <see cref="Formatter"/> with the project-wide formatting rules
/// (four-space indent, "Allman" braces) and post-processes the result so the file
/// ends with LF line endings only and starts with the Gravity auto-generated banner.
/// </summary>
internal static class CSharpFileFormatter
{
    /// <summary>
    /// Format <paramref name="source"/> with Roslyn and prepend the Gravity
    /// auto-generated header. The returned string uses LF line endings and ends
    /// with a single trailing newline.
    /// </summary>
    public static string Format(string source, string sourceGravityRelativePath)
    {
        // Defensive: pin the current thread to invariant culture so any formatter
        // option dependent on culture (e.g. integer parsing of indent sizes) behaves
        // identically across machines.
        var prior = Thread.CurrentThread.CurrentCulture;
        try
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
            var tree = CSharpSyntaxTree.ParseText(source);

            using var workspace = new AdhocWorkspace();
            var options = ConfigureOptions(workspace.Options);
            var formatted = Formatter.Format(tree.GetRoot(), workspace, options).ToFullString();

            // Roslyn may emit CRLF on some platforms; normalize to LF.
            var normalized = formatted.Replace("\r\n", "\n").Replace("\r", "\n");

            // Strip any trailing whitespace lines, then ensure single trailing LF.
            normalized = normalized.TrimEnd('\n', ' ', '\t') + "\n";

            return Header(sourceGravityRelativePath) + normalized;
        }
        finally
        {
            Thread.CurrentThread.CurrentCulture = prior;
        }
    }

    private static OptionSet ConfigureOptions(OptionSet baseOptions)
    {
        return baseOptions
            .WithChangedOption(FormattingOptions.UseTabs, LanguageNames.CSharp, false)
            .WithChangedOption(FormattingOptions.IndentationSize, LanguageNames.CSharp, 4)
            .WithChangedOption(FormattingOptions.TabSize, LanguageNames.CSharp, 4)
            .WithChangedOption(FormattingOptions.NewLine, LanguageNames.CSharp, "\n")
            .WithChangedOption(CSharpFormattingOptions.NewLineForElse, true)
            .WithChangedOption(CSharpFormattingOptions.NewLineForCatch, true)
            .WithChangedOption(CSharpFormattingOptions.NewLineForFinally, true)
            .WithChangedOption(CSharpFormattingOptions.NewLineForMembersInObjectInit, true)
            .WithChangedOption(CSharpFormattingOptions.NewLineForMembersInAnonymousTypes, true)
            .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInTypes, true)
            .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInMethods, true)
            .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInProperties, true)
            .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInAccessors, true)
            .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInAnonymousMethods, true)
            .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInControlBlocks, true)
            .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInLambdaExpressionBody, true);
    }

    private static string Header(string sourceGravityRelativePath)
    {
        var path = sourceGravityRelativePath.Replace('\\', '/');
        return "// <auto-generated>\n"
            + "//     This file was generated by Gravity DSL.\n"
            + "//     Source: " + path + "\n"
            + "// </auto-generated>\n"
            + "\n";
    }
}
